baseURL = 'https://jasonbrave.github.io/'
languageCode = 'en-us'
title = 'Jason Xu'
theme = 'paper'

[params]
  github = 'JasonBrave'
  rss = true

[menu]

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "About Me"
    url = "/about/"
    weight = 10
